all: check ## Build bpxe
	go build ./...
	mkdir -p bin
	go build -o bin ./cmd/bpxe

test: check ## Run tests
	go test ./...

generate: ## Generate source files (only needed if schema changes)
	go generate ./...
	go fmt ./...
	go vet ./...

check: ## Run linters
	go vet ./...
	golangci-lint run
