all: check ## Build bpxe
	go build ./...
	mkdir -p bin
	go build -o bin ./cmd/bpxe

test: check ## Run tests
	go test -count=100 ./pkg/...
	go test ./test/...

headers:
	@go-license --config=.license.yml $(wildcard **/**.go **/**/**.go **/**/**/**.go **/**/**/**/**.go **/**/**/**/**/**.go)

generate: ## Generate source files (only needed if schema changes)
	go generate ./...
	go fmt ./...
	$(MAKE) headers
	go vet ./...

check: ## Run linters
	go vet ./...
	golangci-lint run
